GlobalPlanner:                
  # from source code
  old_navfn_behavior: false
  use_quadratic: false      
  use_dijkstra: true           
  use_grid_path: false  
  allow_unknown: false      
  planner_window_x: 0.0       
  planner_window_y: 0.0  
  default_tolerance: 0.0
  publish_scale: 100 
  outline_map: false

  # from cfg file
  lethal_cost: 253             
  neutral_cost: 50           
  cost_factor: 3          
  publish_potential: false 
  orientation_mode: 1
  orientation_window_size: 1
